### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by DerpgonCz** [vav17/NoobScript-331#5]
So first of all, could you add changing volume with mouse scrolling?

And second, could you add a feature that notifies you when you play or you get notified? I am at school on plug regularly and I dont hear when someone notices me, would be great to make it possible to toggle it on or off (code: http://stackoverflow.com/questions/6092885/what-ways-are-out-there-to-display-a-desktop-notification-from-a-web-app/13328397#13328397)

**Comment by vav17** [comment]
I will add it to the todo list right now! Thats actually a really good idea that I had in mind for a while but never got to do it. Thanks for the feedback!
